### ISSUE TITLE
Define test plan document

### ISSUE THREAD

**Issue by gfrebello** [gfrebello/qs-trip-planning-procedure#13]
A test plan is a document detailing the objectives, resources, and processes for a specific test for a product. This is important to help us test everything that is done in during the development of the project.

Link on Google Docs: https://docs.google.com/document/d/1iroJJxZPw0UjmDqtl8cHm_YGGQ0pO3cwq4V6tQ-vnBc/edit?usp=sharing

**Comment by Berne023** [comment]
Revisado. Comentário deixado em relação a "não haver testes para o front-end". Discordo deste ponto, as funcionalidade são testadas através do próprio front-end, então tem de haver testes para aspectos de front sim (embora não precise ter necessariamente um teste específico para front, o front vai estar embutido nos testes de funcionalidade).
