### ISSUE TITLE
Setup environment (Gabriel)

### ISSUE THREAD

**Issue by Berne023** [gfrebello/qs-trip-planning-procedure#17]
Setup the development environment by installing the JHipster development platform. Installation and setup instructions can be found at https://www.jhipster.tech/

**Comment by gfrebello** [comment]
Succesfully installed JHipster using a Docker image.

**Comment by gfrebello** [comment]
The development environment worked nicely. A "Welcome, Java Hipster" page is displayed when starting the default application.
