### ISSUE TITLE
Create UseCase document

### ISSUE THREAD

**Issue by gfrebello** [gfrebello/qs-trip-planning-procedure#3]
This document will describe the interaction of the users with the system. It should serve as a basis for creating the Class Diagram.

The link to the document is here: https://docs.google.com/document/d/1aBUrWHijlzKa5wgaThEsUfXzS8b8zDXjaW2PjNYcZ2s/edit

It can be found in the following Google Drive folder: https://drive.google.com/drive/folders/12783GBQAYpSUX0QHTZsKf18RXgPDYzYe?usp=sharing

This document will follow the template: https://github.com/utelemaco/prisma-sandbox-project/wiki/Use-Case-Template

**Comment by Berne023** [comment]
Revisado. Comentários feitos no documento a respeito de possível inclusão/modificação de alguns casos de uso.
