### ISSUE TITLE
Meeting with stakeholders

### ISSUE THREAD

**Issue by gfrebello** [gfrebello/qs-trip-planning-procedure#5]
Setup a meeting with Toacy, Rachel and Ulisses. The meeting should discuss the system's requirements and validate the proposed milestone schedule. 

The following template will be used: https://github.com/utelemaco/prisma-sandbox-project/wiki/Meeting-Report-Template

Meeting with Traveler: https://docs.google.com/document/d/1ZVMsIZrnaI-hbJsBrzrEnfzPoBT26G5-DqhTBIy-A-I/edit?usp=sharing

**Comment by Berne023** [comment]
Possíveis perguntas para o stakeholder "Viajante":

Você acha necessário ter que se conectar para planejar cada viagem? Ou prefere dar as informações necessárias a cada planejamento no lugar de ter um login obrigatório?

Você gostaria de usar o produto para, por exemplo, apenas ver e reservar atrações, ou há alguma funcionalidade que você sente que usaria sempre (eg. obrigatório reservar vôo).

Quais tipos de acomodações você gostaria de ter acesso (hotéis, hostels, airbnb, etc).

Ter filtros para essas informações seria útil? (Eg. apenas mostrar hotéis/atrações até um certo preço). Se sim, quais filtros você acha que são importantes?

Em relação aos seguros viagem, o que você gostaria que estivesse incluído obrigatoriamente?

Que meios de pagamentos você gostaria de ter acesso?

Para que o site se mantenha, uma taxa de conveniência teria de ser cobrada. O quanto você estaria disposto a pagar para usar o serviço?

**Comment by Berne023** [comment]
Respostas para "Viajante":

1. Armazenar o que o cara faz. Interessante ter login. Até para salvar o planejamento. Guardar um cookie talvez?

2. Nada obrigatório, tudo opcional.

3. Já está no KIP-Pages

4. Qualquer tipo de acomodação, fica a nosso critério.

5. Preço, local, tipo (de acomodação, de atração), classificação 

6. No nosso caso “quer fazer? Quanto é? Acabou”, voo atrasado, mala perdida, seguro medico também, seguro que engloba carro alugado, etc.

7. Cartão e boleto, dinheiro na agencia

8. Taxa de serviço, deixar configurado, não se preocupar muito com o valor exato.
